services:
  - type: web
    name: bodega-backend
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: APP_NAME
        value: Camuchita Backend
      - key: APP_VERSION
        value: 1.0.0
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: API_PREFIX
        value: /api
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
